<?php $blog = $block->getDataBlogId(); ?>
<div class="content-heading">
    <h2 class="title">Edit Blogs </h2>
</div>
<div class="content-blog">
    <div class="edit-frm">
        <form action="<?php echo $block->getFormActionEdit();?>" method="POST">
            <div class="form-group">
                <label>Content</label>
                <textarea name="content" class="form-control" id="content" rows="8"><?php echo $blog['content'];?></textarea>
            </div>
            <div class="form-group">
                <label>Status</label>
                <select name="status" id="">
                    <?php if ($blog['status'] == 1){?>
                        <option value="1" selected>publish</option>-->
                        <option value="2">draft</option>
                        <option value="3">non-publish</option>
                    <?php }?>
                    <?php if ($blog['status'] == 2){?>
                        <!--<option value="1" >publish</option>-->
                        <option value="2" selected>draft</option>
                        <option value="3">non-publish</option>
                    <?php }?>
                    <?php if ($blog['status'] == 3){?>
                        <!--            <option value="1" >publish</option>-->
                        <option value="2" >draft</option>
                        <option value="3" selected>non-publish</option>
                    <?php }?>
                </select>
                <input type="hidden" name="blog_id" value="<?php echo $blog['id'];?>">
                <input type="hidden" name="author_id" value="<?php echo $blog['author_id'];?>">
            </div>
            <button class="btn-edit edit action-primary" type="submit" style="width: 130px;padding: 15px;"><span style="font-size: 20px">Edit</span></button>
        </form>
    </div>
</div>

<script>
    require([
        "jquery",
        "mage/translate",
        "mage/adminhtml/events",
        "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function(jQuery){
        wysiwygcompany_description = new wysiwygSetup("content", {
            "width":"99%",  // defined width of editor
            "height":"200px", // height of editor
            "plugins":[{"name":"image"}], // for image
            "tinymce4":{"toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
            }
        });
        wysiwygcompany_description.setup("exact");
    });
</script>

